Repository CodeForAfrica/COMMONS-UI, pull requests merged in 2020-05, with the labels that each got.

#19 [HotFix] Lists
  packages/core/src/ListItem/index.js
  packages/core/src/ListItem/useStyles.js
  packages/core/src/ProfileList/index.js
  packages/core/src/ProfileList/useStyles.js
  packages/core/src/StoryList/index.js
  packages/core/src/StoryList/useStyles.js
  yarn.lock
Labels: bug, dependencies

#20 [HotFix] Fix initial scroll to ProfileList
  packages/core/src/ProfileList/index.js
  packages/core/src/StoryList/index.js
  stories/components.stories.js
Labels: breaking change, bug, enhancement

#21 [HotFix] Footer
  packages/core/src/Footer/Initiative.js
  packages/core/src/Footer/index.js
  stories/footer.stories.js
Labels: bug, enhancement

#22 [HotFix] Datasets and Documents
  packages/core/src/DocumentsAndDatasets/Content.js
  packages/core/src/DocumentsAndDatasets/index.js
  packages/core/src/DocumentsAndDatasets/useStyles.js
  stories/assets/illo-02.png
  stories/assets/images/illo-02.png
  stories/assets/images/illo-02@2x.png
  stories/components.stories.js
Labels: breaking change, bug, enhancement

#23 [HotFix] Documents and Datasets
  packages/core/src/DocumentsAndDatasets/Content.js
  packages/core/src/DocumentsAndDatasets/Desktop/index.js
  packages/core/src/DocumentsAndDatasets/Mobile/index.js
  packages/core/src/DocumentsAndDatasets/index.js
  packages/core/src/DocumentsAndDatasets/useStyles.js
  stories/components.stories.js
Labels: breaking change, bug, enhancement

#24 ScrollBar
  packages/core/src/DocumentsAndDatasets/Desktop/index.js
  packages/core/src/DocumentsAndDatasets/useStyles.js
  packages/core/src/Footer/index.js
  packages/core/src/ProfileList/index.js
  packages/core/src/ScrollBar/index.js
  packages/core/src/ScrollableGridList/index.js
  packages/core/src/index.js
Labels: bug, enhancement, feature

#25 [Hotfix] Add Item Children in ListItem
  packages/core/src/ListItem/index.js
  packages/core/src/ProfileList/index.js
Labels: enhancement
