Repository CodeForAfrica/COMMONS-UI, pull requests merged in 2020-04, with the labels that each got.

#1 #172101652: Project initial setup
  .eslintignore
  .eslintrc.js
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc
  .storybook/addons.js
  .storybook/config.js
  LICENSE.md
  README.md
  babel.config.js
  lerna.json
  package.json
  packages/README.md
  packages/core/package.json
  packages/core/src/components/Core.jsx
  packages/core/src/index.js
  stories/index.stories.js
  yarn.lock
Labels: documentation, enhancement

#2 Deploy to GH Pages
  package.json
  yarn.lock
Labels: dependencies, feature

#4 Custom storybook babel should exist within .storybook
  .storybook/.babelrc
Labels: bug

#3 Setup showcase component
  .eslintrc.js
  package.json
  packages/core/package.json
  packages/core/src/components/Core.jsx
  packages/core/src/components/Showcase/StoryCard.js
  packages/core/src/components/Showcase/StoryList.js
  packages/core/src/components/Showcase/index.js
  packages/core/src/index.js
  stories/index.stories.js
  stories/showcase.stories.js
  yarn.lock
Labels: feature

#7 #172241824 Link Component
  packages/core/src/components/A.js
Labels: feature

#9 Lists (Profile & Story)
  .eslintrc.js
  .prettierrc
  .storybook/.babelrc
  babel.config.js
  jsconfig.json
  package.json
  packages/core/package.json
  packages/core/src/ProfileList/Profile/index.js
  packages/core/src/ProfileList/Profile/useStyles.js
  packages/core/src/ProfileList/index.js
  packages/core/src/ProfileList/useStyles.js
  packages/core/src/ScrollableGridList/index.js
  packages/core/src/StoryList/StoryCard.js
  packages/core/src/StoryList/StoryList.js
  packages/core/src/StoryList/index.js
  packages/core/src/components/Showcase/StoryList.js
  packages/core/src/components/Showcase/index.js
  packages/core/src/index.js
  stories/NavigationButton/index.js
  stories/NavigationButton/useStyles.js
  stories/assets/person_1.png
  stories/assets/person_1@2x.png
  stories/assets/person_2.png
  stories/assets/person_2@2x.png
  stories/assets/person_3.png
  stories/assets/person_3@2x.png
  stories/assets/tile-1@1x-100.png
  stories/assets/tile-1@1x-100@2x.png
  stories/assets/tile-2@1x-100.png
  stories/assets/tile-2@1x-100@2x.png
  stories/assets/tile-3@1x-100.png
  stories/assets/tile-3@1x-100@2x.png
  stories/components.stories.js
  stories/showcase.stories.js
  stories/utils.js
  yarn.lock
Labels: dependencies, enhancement, feature

#10 [Chore] Publish Setup
  lerna.json
  package.json
  packages/core/src/A.js
  packages/core/src/components/A.js
  packages/core/src/index.js
  yarn.lock
Labels: breaking change, bug, enhancement

#5 Setup footer component
  packages/core/package.json
  packages/core/src/About.js
  packages/core/src/Footer/Initiative.js
  packages/core/src/Footer/QuickLinks.js
  packages/core/src/Footer/StayInTouch.js
  packages/core/src/Footer/Title.js
  packages/core/src/Footer/index.js
  packages/core/src/Layout.js
  packages/core/src/RichTypography.js
  packages/core/src/Section.js
  packages/core/src/index.js
  stories/assets/cfa.png
  stories/assets/email.svg
  stories/assets/facebook.svg
  stories/assets/group-3-copy.svg
  stories/assets/group-3.svg
  stories/assets/pulitzer.png
  stories/assets/twitter.svg
  stories/footer.stories.js
  yarn.lock
Labels: feature

#6 Document & Dataset component
  packages/core/.yarnrc
  packages/core/package.json
  packages/core/src/About.js
  packages/core/src/DocumentsAndDatasets/Content.js
  packages/core/src/DocumentsAndDatasets/index.js
  packages/core/src/DocumentsAndDatasets/useStyles.js
  packages/core/src/Footer/QuickLinks.js
  packages/core/src/Footer/StayInTouch.js
  packages/core/src/Footer/Title.js
  packages/core/src/Footer/index.js
  packages/core/src/Layout.js
  packages/core/src/RichTypography.js
  packages/core/src/Section.js
  packages/core/src/index.js
  stories/assets/images/illo-02.png
  stories/assets/images/illo-02@2x.png
  stories/components.stories.js
  stories/footer.stories.js
  yarn.lock
Labels: feature

#11 [HotFix] Utility Components
  packages/core/src/Layout.js
  packages/core/src/RichTypography.js
  packages/core/src/Section.js
  packages/core/src/index.js
Labels: bug, enhancement, feature

#12 [Hotfix] Footer Stay in Touch component
  packages/core/src/Footer/StayInTouch.js
  packages/core/src/Footer/index.js
  stories/footer.stories.js
Labels: breaking change, bug

#13 [Hotfix] Utility Components
  packages/core/src/Layout.js
  packages/core/src/RichTypography.js
Labels: bug, enhancement

#15 [HotFix] Components
  packages/core/src/A.js
  packages/core/src/DocumentsAndDatasets/Content.js
  packages/core/src/DocumentsAndDatasets/index.js
  packages/core/src/DocumentsAndDatasets/useStyles.js
  packages/core/src/Footer/StayInTouch.js
  stories/components.stories.js
Labels: bug

#17 [HotFix] Footer
  packages/core/src/Footer/LegalLinks.js
  packages/core/src/Footer/StayInTouch.js
  packages/core/src/Footer/index.js
Labels: bug

#18 Fix ProfileList component
  packages/core/src/DocumentsAndDatasets/Content.js
  packages/core/src/Footer/index.js
  packages/core/src/ProfileList/useStyles.js
Labels: bug
