Repository CodeForAfrica/COMMONS-UI, pull requests merged in 2020-06, with the labels that each got.

#26 [HotFix] Footer
  packages/core/src/Footer/About.js
  packages/core/src/Footer/Initiative.js
  packages/core/src/Footer/LegalLinks.js
  packages/core/src/Footer/QuickLinks.js
  packages/core/src/Footer/index.js
  stories/footer.stories.js
Labels: breaking change, bug, enhancement

#28 [HotFix] Section/Layout classes props
  package.json
  packages/core/src/Layout.js
  packages/core/src/Section.js
  yarn.lock
Labels: bug, dependencies

#29 [HotFix] oneOfType requires an array
  packages/core/src/ScrollBar/index.js
  packages/core/src/ScrollableGridList/index.js
  packages/core/src/StoryList/StoryList.js
Labels: bug

#30 [Feature] Feature variants
  .editorconfig
  .storybook/addons.js
  .storybook/config.js
  .storybook/main.js
  .storybook/manager.js
  package.json
  packages/core/src/Footer/PrimaryFooter.js
  packages/core/src/Footer/SecondaryFooter.js
  packages/core/src/Footer/index.js
  packages/core/src/Footer/useStyles.js
  packages/core/src/ScrollBar/index.js
  stories/components.stories.js
  stories/footer.stories.js
  yarn.lock
Labels: dependencies, enhancement, feature

#31 [Feature] Footer contacts
  packages/core/src/Footer/PrimaryFooter.js
  packages/core/src/Footer/SecondaryFooter.js
  packages/core/src/Footer/StayInTouch.js
  packages/core/src/Footer/useStyles.js
  stories/footer.stories.js
Labels: breaking change, bug, enhancement, feature

#32 Add Filter component
  packages/core/src/Filter.js
  packages/core/src/index.js
  stories/components.stories.js
Labels: enhancement
