Repository CodeForAfrica/COMMONS-UI, pull requests merged in 2020-09, with the labels that each got.

#38 [Chore] Project setup
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .storybook/main.js
  .storybook/manager.js
  LICENSE.md
  README.md
  lerna.json
  package.json
  packages/README.md
  yarn.lock
Labels: chore, dependencies

#37 Feature modular footer Components
  packages/core/src/Footer/About.js
  packages/core/src/Footer/About/About.js
  packages/core/src/Footer/About/Initiative.js
  packages/core/src/Footer/About/index.js
  packages/core/src/Footer/Initiative.js
  packages/core/src/Footer/Logo.js
  packages/core/src/Footer/PrimaryFooter.js
  packages/core/src/Footer/index.js
  packages/core/src/Footer/useStyles.js
  packages/core/src/index.js
  stories/footer.stories.js
Labels: enhancement

#39 clean up
  packages/core/src/Footer/About/index.js
  packages/core/src/Footer/Logo.js
  packages/core/src/Footer/PrimaryFooter.js
  packages/core/src/Footer/index.js
  packages/core/src/Footer/useStyles.js
Labels: chore
