Repository CodeForAfrica/COMMONS-UI, pull requests merged in 2021-02, with the labels that each got.

#50 Datasets && Documents Content
  packages/core/src/DataSourceContent/Content.js
  packages/core/src/DataSourceContent/index.js
  packages/core/src/DataSourceContent/useStyles.js
  packages/core/src/DocumentsAndDatasets/Desktop/index.js
  packages/core/src/DocumentsAndDatasets/Mobile/index.js
  packages/core/src/index.js
  stories/components.stories.js
  stories/footer.stories.js
Labels: enhancement

#55 Fix/initiative logo
  packages/core/src/Footer/PrimaryFooter.js
  packages/core/src/Footer/index.js
  packages/core/src/InitiativeLogo/index.js
  packages/core/src/index.js
  stories/components.stories.js
  stories/footer.stories.js
Labels: bug

#53 Card List Item
  stories/components.stories.js
Labels: chore

#52 Rearrange storybook components
  packages/core/src/AboutOrganization/About.js
  packages/core/src/AboutOrganization/Initiative.js
  packages/core/src/AboutOrganization/index.js
  packages/core/src/AboutOrganization/useStyles.js
  packages/core/src/DocumentsAndDatasets/Desktop/index.js
  packages/core/src/DocumentsAndDatasets/Mobile/index.js
  packages/core/src/DocumentsAndDatasets/index.js
  packages/core/src/DocumentsAndDatasets/useStyles.js
  packages/core/src/Filter/index.js
  packages/core/src/Footer/PrimaryFooter.js
  packages/core/src/Footer/SecondaryFooter.js
  packages/core/src/Footer/index.js
  packages/core/src/InitiativeLogo/index.js
  packages/core/src/InitiativeLogo/useStyles.js
  packages/core/src/ProfileList/Contacts/index.js
  packages/core/src/ProfileList/index.js
  packages/core/src/ProfileList/useStyles.js
  packages/core/src/QuickLinks/index.js
  packages/core/src/StoryList/index.js
  packages/core/src/StoryList/useStyles.js
  packages/core/src/index.js
  stories/components.stories.js
  stories/footer.stories.js
  yarn.lock
Labels: enhancement
